### ISSUE TITLE
Tile server is not updatingthe map with the latest dev build of minetest

### ISSUE THREAD

**Issue by Ryan-Nolan** [thomasrudin-mt/minetest-tile-server#41]
Since i updated to the latest minetest commit the tile server doesn't seem to be generating/updating the map.

I've attached a copy of the tileserver logs(in debug mode)
https://gist.github.com/Ryan-Nolan/246a9ea4130bc1168111f0fe037ce9e7

**Comment by thomasrudin** [comment]
are you sure its because of the new minetest version/build and did not appear before too?
The tileserver has currently some "hiccups" when it comes to rendering new tiles.
Sometimes a player has to visit the place a couple of times until changes appear on the map.

That said:
I'm working on better modularity and a proper test-setup (#37) now and think that will prevent such issues in the future.
There are some things that don't scale well with the current code (mainly poi/items on the map as they are fetched as a whole and not position-dependent: #42).

**Comment by Ryan-Nolan** [comment]
I'm not sure whats caused it if I'm being honest. its been an issue for me for a few days. even ever multiple visits at different times of the day it still doesn't render or re render the tiles.
